export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"

export const SINGLE_PRODUCTS_REQUEST = "SINGLE_PRODUCTS_REQUEST";
export const SINGLE_PRODUCTS_SUCCESS = "SINGLE_PRODUCTS_SUCCESS";
export const SINGLE_PRODUCTS_ERROR = "SINGLE_PRODUCTS_ERROR";